backup-tools/awscli-exe-linux-x86_64.zip:
  size: 66781495
  sha: sha256:25f24e492074be063be04bd1308137e5cb3e55d31095a0ca7624564c2d128193
cf-cli/cf8-cli-8.8.2-linux64.tgz:
  size: 9377091
  sha: sha256:5f8a0c12a257b0eaf90f0d98cfcb617d1c0e2360e43cda4e64045c0f5a50248d
golang/go1.21.6.linux-amd64.tar.gz:
  size: 66704768
  sha: sha256:3f934f40ac360b9c01f616a9aa1796d227d8b0328bf64cb045c7b8c4ee9caea4
otel-collector/otelcol-contrib.tar.gz:
  size: 64650989
  sha: sha256:c3857481e9eb7319cd1e6978ed76c2a9e934400cdacf7a6b696579a858fde3ef
seaweedfs-broker/seaweedfs-broker.tar.gz:
  size: 3422958
  sha: sha256:79101f408fcc52dff7abe4bec205ff81641aad1fcf404318368416a5aefd5743
seaweedfs/linux_amd64.tar.gz:
  size: 40265195
  sha: sha256:61c8a132c6753cc6726ab6dcc761e0fb2ae2bf7310b1276e82427f4a33dc2a7b
