cf-cli/cf8-cli-8.8.2-linux64.tgz:
  size: 9377091
  sha: sha256:5f8a0c12a257b0eaf90f0d98cfcb617d1c0e2360e43cda4e64045c0f5a50248d
golang/go1.21.6.linux-amd64.tar.gz:
  size: 66704768
  sha: sha256:3f934f40ac360b9c01f616a9aa1796d227d8b0328bf64cb045c7b8c4ee9caea4
seaweedfs-broker/seaweedfs-broker.tar.gz:
  size: 104354
  sha: sha256:6dfb92090ee2c4627e39bc473714d4999b32597e644666b4c2b759197dd77750
seaweedfs/linux_amd64.tar.gz:
  size: 40265195
  sha: sha256:61c8a132c6753cc6726ab6dcc761e0fb2ae2bf7310b1276e82427f4a33dc2a7b
