backup-tools/awscli-exe-linux-x86_64.zip:
  size: 66781495
  sha: sha256:25f24e492074be063be04bd1308137e5cb3e55d31095a0ca7624564c2d128193
cf-cli/cf8-cli-8.8.2-linux64.tgz:
  size: 9377091
  sha: sha256:5f8a0c12a257b0eaf90f0d98cfcb617d1c0e2360e43cda4e64045c0f5a50248d
golang/go1.21.6.linux-amd64.tar.gz:
  size: 66704768
  sha: sha256:3f934f40ac360b9c01f616a9aa1796d227d8b0328bf64cb045c7b8c4ee9caea4
otel-collector/otelcol-contrib.tar.gz:
  size: 64650989
  sha: sha256:c3857481e9eb7319cd1e6978ed76c2a9e934400cdacf7a6b696579a858fde3ef
postgresql-client/postgresql-16.4.tar.bz2:
  size: 24765786
  sha: sha256:971766d645aa73e93b9ef4e3be44201b4f45b5477095b049125403f9f3386d6f
seaweedfs-broker/seaweedfs-broker.tar.gz:
  size: 3424678
  sha: sha256:e8e34a89697a06bc3b8f99b0cd181a8e7a109d8211d34f260a1f079489b7a108
seaweedfs/linux_amd64.tar.gz:
  size: 50164114
  sha: sha256:64ec9f243977adda9b82cb288db47552aa2cef06b3a4f3a794eca69751a9ca13
